[info]
game-name = "twwgz"
full-game-name = "The Wind Waker Practice Rom"
developer-name = "The Wind Waker / Twilight Princess Community"
full-developer-name = "The Wind Waker / Twilight Princess Community"

[src]
iso = "@srcIso"
patch = "regional-patch.asm"
map = "@srcMap"

[build]
map = "@bldMap"
iso = "@bldIso"

[link]
entries = ["apply_lib_hooks"]
base = "@linkBase"
libs = ["twwgz.a", "external/gcn_c/gcn_c.a"]

[files]
# textures
"twwgz/tex/blank.tex" = "res/tex/blank.tex"
"twwgz/tex/twwgz.tex" = "res/tex/twwgz.tex"

# fonts
"twwgz/fonts/consola.fnt" = "res/fonts/consola.fnt"
"twwgz/fonts/calamity-bold.fnt" = "res/fonts/calamity-bold.fnt"
"twwgz/fonts/lib-sans-bold.fnt" = "res/fonts/lib-sans-bold.fnt"
"twwgz/fonts/lib-sans.fnt" = "res/fonts/lib-sans.fnt"
"twwgz/fonts/lib-serif-bold.fnt" = "res/fonts/lib-serif-bold.fnt"
"twwgz/fonts/lib-serif.fnt" = "res/fonts/lib-serif.fnt"
"twwgz/fonts/press-start-2p.fnt" = "res/fonts/press-start-2p.fnt"

# save_files
"twwgz/save_files/any_no_mss.bin" = "res/save_files/any_no_mss.bin"
"twwgz/save_files/any_percent.bin" = "res/save_files/any_percent.bin"
"twwgz/save_files/all_dungeons.bin" = "res/save_files/all_dungeons.bin"
"twwgz/save_files/any_no_mss/after_intro.bin" = "res/save_files/any_no_mss/after_intro.bin"
"twwgz/save_files/any_no_mss/orca.bin" = "res/save_files/any_no_mss/orca.bin"
"twwgz/save_files/any_no_mss/forest_of_fairies.bin" = "res/save_files/any_no_mss/forest_of_fairies.bin"
"twwgz/save_files/any_no_mss/ropes_1.bin" = "res/save_files/any_no_mss/ropes_1.bin"
"twwgz/save_files/any_no_mss/ff1.bin" = "res/save_files/any_no_mss/ff1.bin"
"twwgz/save_files/any_no_mss/windfall.bin" = "res/save_files/any_no_mss/windfall.bin"
"twwgz/save_files/any_no_mss/bombs_swim.bin" = "res/save_files/any_no_mss/bombs_swim.bin"
"twwgz/save_files/any_no_mss/ropes_2.bin" = "res/save_files/any_no_mss/ropes_2.bin"
"twwgz/save_files/any_no_mss/forest_haven_swim.bin" = "res/save_files/any_no_mss/forest_haven_swim.bin"
"twwgz/save_files/any_no_mss/dtcs.bin" = "res/save_files/any_no_mss/dtcs.bin"
"twwgz/save_files/any_no_mss/quiver_swim.bin" = "res/save_files/any_no_mss/quiver_swim.bin"
"twwgz/save_files/any_no_mss/ff2_swim.bin" = "res/save_files/any_no_mss/ff2_swim.bin"
"twwgz/save_files/any_no_mss/helmaroc_skip.bin" = "res/save_files/any_no_mss/helmaroc_skip.bin"
"twwgz/save_files/any_no_mss/barrier_skip.bin" = "res/save_files/any_no_mss/barrier_skip.bin"
"twwgz/save_files/any_no_mss/trials_skip.bin" = "res/save_files/any_no_mss/trials_skip.bin"
"twwgz/save_files/any_no_mss/puppet_ganon.bin" = "res/save_files/any_no_mss/puppet_ganon.bin"
"twwgz/save_files/any_no_mss/morth_hover.bin" = "res/save_files/any_no_mss/morth_hover.bin"
"twwgz/save_files/any_no_mss/ganondorf.bin" = "res/save_files/any_no_mss/ganondorf.bin"
"twwgz/save_files/any_percent/mss.bin" = "res/save_files/any_percent/mss.bin"
"twwgz/save_files/any_percent/pmss.bin" = "res/save_files/any_percent/pmss.bin"
"twwgz/save_files/any_percent/bombs.bin" = "res/save_files/any_percent/bombs.bin"
"twwgz/save_files/any_percent/sailskip.bin" = "res/save_files/any_percent/sailskip.bin"
"twwgz/save_files/any_percent/ropes2.bin" = "res/save_files/any_percent/ropes2.bin"
"twwgz/save_files/any_percent/fhswim.bin" = "res/save_files/any_percent/fhswim.bin"
"twwgz/save_files/any_percent/dtcs.bin" = "res/save_files/any_percent/dtcs.bin"
"twwgz/save_files/any_percent/lh.bin" = "res/save_files/any_percent/lh.bin"
"twwgz/save_files/any_percent/quiver.bin" = "res/save_files/any_percent/quiver.bin"
"twwgz/save_files/any_percent/ff2.bin" = "res/save_files/any_percent/ff2.bin"
"twwgz/save_files/any_percent/helm.bin" = "res/save_files/any_percent/helm.bin"
"twwgz/save_files/any_percent/bs.bin" = "res/save_files/any_percent/bs.bin"
"twwgz/save_files/any_percent/trials.bin" = "res/save_files/any_percent/trials.bin"
"twwgz/save_files/any_percent/las.bin" = "res/save_files/any_percent/las.bin"
"twwgz/save_files/any_percent/pgcs.bin" = "res/save_files/any_percent/pgcs.bin"
"twwgz/save_files/any_percent/pgs.bin" = "res/save_files/any_percent/pgs.bin"
"twwgz/save_files/any_percent/pg.bin" = "res/save_files/any_percent/pg.bin"
"twwgz/save_files/any_percent/morth.bin" = "res/save_files/any_percent/morth.bin"
"twwgz/save_files/any_percent/ganon.bin" = "res/save_files/any_percent/ganon.bin"
"twwgz/save_files/all_dungeons/mss.bin" = "res/save_files/all_dungeons/mss.bin"
"twwgz/save_files/all_dungeons/pmss.bin" = "res/save_files/all_dungeons/pmss.bin"
"twwgz/save_files/all_dungeons/ff1c.bin" = "res/save_files/all_dungeons/ff1c.bin"
"twwgz/save_files/all_dungeons/sail.bin" = "res/save_files/all_dungeons/sail.bin"
"twwgz/save_files/all_dungeons/ropes2.bin" = "res/save_files/all_dungeons/ropes2.bin"
"twwgz/save_files/all_dungeons/fhswim.bin" = "res/save_files/all_dungeons/fhswim.bin"
"twwgz/save_files/all_dungeons/oh.bin" = "res/save_files/all_dungeons/oh.bin"
"twwgz/save_files/all_dungeons/dtcs.bin" = "res/save_files/all_dungeons/dtcs.bin"
"twwgz/save_files/all_dungeons/fw.bin" = "res/save_files/all_dungeons/fw.bin"
"twwgz/save_files/all_dungeons/kd.bin" = "res/save_files/all_dungeons/kd.bin"
"twwgz/save_files/all_dungeons/afw.bin" = "res/save_files/all_dungeons/afw.bin"
"twwgz/save_files/all_dungeons/drc.bin" = "res/save_files/all_dungeons/drc.bin"
"twwgz/save_files/all_dungeons/odrc.bin" = "res/save_files/all_dungeons/odrc.bin"
"twwgz/save_files/all_dungeons/dbks.bin" = "res/save_files/all_dungeons/dbks.bin"
"twwgz/save_files/all_dungeons/gohma.bin" = "res/save_files/all_dungeons/gohma.bin"
"twwgz/save_files/all_dungeons/adrc.bin" = "res/save_files/all_dungeons/adrc.bin"
"twwgz/save_files/all_dungeons/aj.bin" = "res/save_files/all_dungeons/aj.bin"
"twwgz/save_files/all_dungeons/totg.bin" = "res/save_files/all_dungeons/totg.bin"
"twwgz/save_files/all_dungeons/dn.bin" = "res/save_files/all_dungeons/dn.bin"
"twwgz/save_files/all_dungeons/a2s.bin" = "res/save_files/all_dungeons/a2s.bin"
"twwgz/save_files/all_dungeons/gohdan.bin" = "res/save_files/all_dungeons/gohdan.bin"
"twwgz/save_files/all_dungeons/ps.bin" = "res/save_files/all_dungeons/ps.bin"
"twwgz/save_files/all_dungeons/he.bin" = "res/save_files/all_dungeons/he.bin"
"twwgz/save_files/all_dungeons/bs.bin" = "res/save_files/all_dungeons/bs.bin"
"twwgz/save_files/all_dungeons/ts.bin" = "res/save_files/all_dungeons/booms.bin"
"twwgz/save_files/all_dungeons/booms.bin" = "res/save_files/all_dungeons/ts.bin"
"twwgz/save_files/all_dungeons/phg.bin" = "res/save_files/all_dungeons/phg.bin"
"twwgz/save_files/all_dungeons/ff2c.bin" = "res/save_files/all_dungeons/ff2c.bin"
"twwgz/save_files/all_dungeons/h2s.bin" = "res/save_files/all_dungeons/h2s.bin"
"twwgz/save_files/all_dungeons/aff2.bin" = "res/save_files/all_dungeons/aff2.bin"
"twwgz/save_files/all_dungeons/bfm.bin" = "res/save_files/all_dungeons/bfm.bin"
"twwgz/save_files/all_dungeons/eet.bin" = "res/save_files/all_dungeons/eet.bin"
"twwgz/save_files/all_dungeons/et.bin" = "res/save_files/all_dungeons/et.bin"
"twwgz/save_files/all_dungeons/ss.bin" = "res/save_files/all_dungeons/ss.bin"
"twwgz/save_files/all_dungeons/jal.bin" = "res/save_files/all_dungeons/jal.bin"
"twwgz/save_files/all_dungeons/aet.bin" = "res/save_files/all_dungeons/aet.bin"
"twwgz/save_files/all_dungeons/air.bin" = "res/save_files/all_dungeons/air.bin"
"twwgz/save_files/all_dungeons/amak.bin" = "res/save_files/all_dungeons/amak.bin"
"twwgz/save_files/all_dungeons/wt.bin" = "res/save_files/all_dungeons/wt.bin"
"twwgz/save_files/all_dungeons/wizz.bin" = "res/save_files/all_dungeons/wizz.bin"
"twwgz/save_files/all_dungeons/ahs.bin" = "res/save_files/all_dungeons/ahs.bin"
"twwgz/save_files/all_dungeons/molgera.bin" = "res/save_files/all_dungeons/molgera.bin"
"twwgz/save_files/all_dungeons/awt.bin" = "res/save_files/all_dungeons/awt.bin"
"twwgz/save_files/all_dungeons/fcp.bin" = "res/save_files/all_dungeons/fcp.bin"
"twwgz/save_files/all_dungeons/pgcs.bin" = "res/save_files/all_dungeons/pgcs.bin"
"twwgz/save_files/all_dungeons/pgs.bin" = "res/save_files/all_dungeons/pgs.bin"
"twwgz/save_files/all_dungeons/pg.bin" = "res/save_files/all_dungeons/pg.bin"
"twwgz/save_files/all_dungeons/gd.bin" = "res/save_files/all_dungeons/gd.bin"

# menu
"twwgz/mn/Menu1.dat" = "res/menu/EN_Menu1.dat"
