[info]
game-name = "twwgz"
full-game-name = "The Wind Waker Practice Rom"
developer-name = "The Wind Waker / Twilight Princess Community"
full-developer-name = "The Wind Waker / Twilight Princess Community"

[src]
iso = "@srcIso"
patch = "regional-patch.asm"
map = "@srcMap"

[build]
map = "@bldMap"
iso = "@bldIso"

[link]
entries = ["apply_lib_hooks"]
base = "@linkBase"
libs = ["twwgz.a", "external/gcn_c/gcn_c.a"]

[files]
# textures
"twwgz/tex/blank.tex" = "res/tex/blank.tex"
"twwgz/tex/twwgz.tex" = "res/tex/twwgz.tex"

# fonts
"twwgz/fonts/consola.fnt" = "res/fonts/consola.fnt"
"twwgz/fonts/calamity-bold.fnt" = "res/fonts/calamity-bold.fnt"
"twwgz/fonts/lib-sans-bold.fnt" = "res/fonts/lib-sans-bold.fnt"
"twwgz/fonts/lib-sans.fnt" = "res/fonts/lib-sans.fnt"
"twwgz/fonts/lib-serif-bold.fnt" = "res/fonts/lib-serif-bold.fnt"
"twwgz/fonts/lib-serif.fnt" = "res/fonts/lib-serif.fnt"
"twwgz/fonts/press-start-2p.fnt" = "res/fonts/press-start-2p.fnt"

# save_files
"twwgz/save_files/any_no_mss.bin" = "res/save_files/any_no_mss.bin"
"twwgz/save_files/any_no_mss/after_intro.bin" = "res/save_files/any_no_mss/after_intro.bin"
"twwgz/save_files/any_no_mss/orca.bin" = "res/save_files/any_no_mss/orca.bin"
"twwgz/save_files/any_no_mss/forest_of_fairies.bin" = "res/save_files/any_no_mss/forest_of_fairies.bin"
"twwgz/save_files/any_no_mss/ropes_1.bin" = "res/save_files/any_no_mss/ropes_1.bin"
"twwgz/save_files/any_no_mss/ff1.bin" = "res/save_files/any_no_mss/ff1.bin"
"twwgz/save_files/any_no_mss/windfall.bin" = "res/save_files/any_no_mss/windfall.bin"
"twwgz/save_files/any_no_mss/bombs_swim.bin" = "res/save_files/any_no_mss/bombs_swim.bin"
"twwgz/save_files/any_no_mss/ropes_2.bin" = "res/save_files/any_no_mss/ropes_2.bin"
"twwgz/save_files/any_no_mss/forest_haven_swim.bin" = "res/save_files/any_no_mss/forest_haven_swim.bin"
"twwgz/save_files/any_no_mss/dtcs.bin" = "res/save_files/any_no_mss/dtcs.bin"
"twwgz/save_files/any_no_mss/quiver_swim.bin" = "res/save_files/any_no_mss/quiver_swim.bin"
"twwgz/save_files/any_no_mss/ff2_swim.bin" = "res/save_files/any_no_mss/ff2_swim.bin"
"twwgz/save_files/any_no_mss/helmaroc_skip.bin" = "res/save_files/any_no_mss/helmaroc_skip.bin"
"twwgz/save_files/any_no_mss/barrier_skip.bin" = "res/save_files/any_no_mss/barrier_skip.bin"
"twwgz/save_files/any_no_mss/trials_skip.bin" = "res/save_files/any_no_mss/trials_skip.bin"
"twwgz/save_files/any_no_mss/puppet_ganon.bin" = "res/save_files/any_no_mss/puppet_ganon.bin"
"twwgz/save_files/any_no_mss/morth_hover.bin" = "res/save_files/any_no_mss/morth_hover.bin"
"twwgz/save_files/any_no_mss/ganondorf.bin" = "res/save_files/any_no_mss/ganondorf.bin"

# menu
"twwgz/mn/Menu1.dat" = "res/menu/EN_Menu1.dat"