[info]
game-name = "twwgz"
full-game-name = "The Wind Waker Practice Rom"
developer-name = "The Wind Waker / Twilight Princess Community"
full-developer-name = "The Wind Waker / Twilight Princess Community"

[src]
iso = "@srcIso"
patch = "regional-patch.asm"
map = "@srcMap"

[build]
map = "@bldMap"
iso = "@bldIso"

[link]
entries = ["apply_lib_hooks"]
base = "@linkBase"
libs = ["twwgz.a", "external/gcn_c/gcn_c.a"]

[files]
# textures
"twwgz/tex/blank.tex" = "res/tex/blank.tex"
"twwgz/tex/twwgz.tex" = "res/tex/twwgz.tex"

# fonts
"twwgz/fonts/consola.fnt" = "res/fonts/consola.fnt"
"twwgz/fonts/calamity-bold.fnt" = "res/fonts/calamity-bold.fnt"
"twwgz/fonts/lib-sans-bold.fnt" = "res/fonts/lib-sans-bold.fnt"
"twwgz/fonts/lib-sans.fnt" = "res/fonts/lib-sans.fnt"
"twwgz/fonts/lib-serif-bold.fnt" = "res/fonts/lib-serif-bold.fnt"
"twwgz/fonts/lib-serif.fnt" = "res/fonts/lib-serif.fnt"
"twwgz/fonts/press-start-2p.fnt" = "res/fonts/press-start-2p.fnt"

# menu
"twwgz/mn/Menu1.dat" = "res/menu/EN_Menu1.dat"